### ISSUE TITLE
Lark error in docker build

### ISSUE THREAD

**Issue by jbaettig** [starkware-libs/cairo-lang#110]
Hi

When running docker build as described in [README.md](https://github.com/starkware-libs/cairo-lang/blob/master/README.md) i get the following error:

`lark.exceptions.ConfigurationError:
 Got 'basic', expected one of ('standard', 'contextual', 'dynamic', 'dynamic_complete')`

Here is the whole stack trace:

```
#15 91.13 Traceback (most recent call last):
#15 91.13   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
#15 91.13     return _run_code(code, main_globals, None,
#15 91.13   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
#15 91.13     exec(code, run_globals)
#15 91.13   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/cairo_compile.py", line 9, in <module>
#15 91.13     from starkware.cairo.lang.compiler.assembler import assemble
#15 91.13   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/assembler.py", line 3, in <module>
#15 91.13     from starkware.cairo.lang.compiler.debug_info import DebugInfo, HintLocation, InstructionLocation
#15 91.13   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/debug_info.py", line 9, in <module>
#15 91.13     from starkware.cairo.lang.compiler.preprocessor.flow import FlowTrackingDataActual
#15 91.13   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/preprocessor/flow.py", line 23, in <module>
#15 91.13     from starkware.cairo.lang.compiler.references import ApDeductionError, FlowTrackingError, Reference
#15 91.14   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/references.py", line 19, in <module>
#15 91.14     from starkware.cairo.lang.compiler.fields import ExpressionAsStr
#15 91.14   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/fields.py", line 4, in <module>
#15 91.14     from starkware.cairo.lang.compiler.parser import parse_expr, parse_type
#15 91.14   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/parser.py", line 40, in <module>
#15 91.14     GRAMMAR_PARSER = get_grammar_parser(grammar=open(GRAMMER_FILE, "r").read())
#15 91.14   File "/app/build/Release/src/starkware/cairo/lang/cairo_lang_venv-site/starkware/cairo/lang/compiler/parser.py", line 22, in get_grammar_parser
#15 91.14     return lark.Lark(
#15 91.15   File "/app/build/Release/python_pip/python3.9/pip_lark_parser/lark/lark.py", line 324, in __init__
#15 91.15     assert_config(lexer, ('standard', 'contextual', 'dynamic', 'dynamic_complete'))
#15 91.15   File "/app/build/Release/python_pip/python3.9/pip_lark_parser/lark/exceptions.py", line 19, in assert_config
#15 91.15     raise ConfigurationError(msg % (value, options))
#15 91.15 lark.exceptions.ConfigurationError: Got 'basic', expected one of ('standard', 'contextual', 'dynamic', 'dynamic_complete')
#15 91.16 Traceback (most recent call last):
#15 91.16   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
#15 91.16     return _run_code(code, main_globals, None,
#15 91.16   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
#15 91.16     exec(code, run_globals)
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/starknet/compiler/compile.py", line 8, in <module>
#15 91.16     from starkware.cairo.lang.compiler.assembler import assemble
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/assembler.py", line 3, in <module>
#15 91.16     from starkware.cairo.lang.compiler.debug_info import DebugInfo, HintLocation, InstructionLocation
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/debug_info.py", line 9, in <module>
#15 91.16     from starkware.cairo.lang.compiler.preprocessor.flow import FlowTrackingDataActual
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/preprocessor/flow.py", line 23, in <module>
#15 91.16     from starkware.cairo.lang.compiler.references import ApDeductionError, FlowTrackingError, Reference
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/references.py", line 19, in <module>
#15 91.16     from starkware.cairo.lang.compiler.fields import ExpressionAsStr
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/fields.py", line 4, in <module>
#15 91.16     from starkware.cairo.lang.compiler.parser import parse_expr, parse_type
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/parser.py", line 40, in <module>
#15 91.16     GRAMMAR_PARSER = get_grammar_parser(grammar=open(GRAMMER_FILE, "r").read())
#15 91.16   File "/app/build/Release/src/starkware/starknet/compiler/starknet_compile_venv-site/starkware/cairo/lang/compiler/parser.py", line 22, in get_grammar_parser
#15 91.16     return lark.Lark(
#15 91.16   File "/app/build/Release/python_pip/python3.9/pip_lark_parser/lark/lark.py", line 324, in __init__
#15 91.16     assert_config(lexer, ('standard', 'contextual', 'dynamic', 'dynamic_complete'))
#15 91.16   File "/app/build/Release/python_pip/python3.9/pip_lark_parser/lark/exceptions.py", line 19, in assert_config
#15 91.16     raise ConfigurationError(msg % (value, options))
#15 91.16 lark.exceptions.ConfigurationError: Got 'basic', expected one of ('standard', 'contextual', 'dynamic', 'dynamic_complete')
#15 91.36 make[3]: *** [src/starkware/starknet/core/os/CMakeFiles/starknet_os_program.dir/build.make:75: src/starkware/starknet/core/os/starknet_os_compiled.json] Error 1
#15 91.36 make[2]: *** [CMakeFiles/Makefile2:16072: src/starkware/starknet/core/os/CMakeFiles/starknet_os_program.dir/all] Error 2
#15 91.36 make[2]: *** Waiting for unfinished jobs....
#15 91.37 make[3]: *** [src/starkware/starknet/third_party/open_zeppelin/CMakeFiles/compile_open_zeppelin_account.dir/build.make:75: src/starkware/starknet/third_party/open_zeppelin/account.json] Error 1
#15 91.37 make[2]: *** [CMakeFiles/Makefile2:20215: src/starkware/starknet/third_party/open_zeppelin/CMakeFiles/compile_open_zeppelin_account.dir/all] Error 2
#15 91.37 make[1]: *** [CMakeFiles/Makefile2:7871: src/starkware/cairo/lang/CMakeFiles/cairo_lang_package_venv.dir/rule] Error 2
#15 91.37 make: *** [Makefile:2604: cairo_lang_package_venv] Error 2
```

I get this error since lark was updated recently (#88). Previously i was able to build with docker.

**Comment by jbaettig** [comment]
This issue was solved in v0.10.1 with commit 55a26f4228dcff9c51d3d6bfd5e6638bafe63101
