### ISSUE TITLE
Environment variables not working

### ISSUE THREAD

**Issue by piwonskp** [starkware-libs/cairo-lang#118]
Hi Cairo team,

CLI ignores `STARKNET_GATEWAY_URL` and `STARKNET_FEEDER_GATEWAY_URL` environment variables. Commands work only if these are passed via command line arguments.

### STARKNET_FEEDER_GATEWAY_URL
```
/usr/src/app/sample-contracts # starknet deploy --no_wallet --contract hello.json --gateway_url http://devnet:5050
Deploy transaction was sent.
Contract address: 0x07af9c251859892395187bd59e28fc8f0670bd75137e7b2a1044f2a58efaf353
Transaction hash: 0x4b37c61e76f0ea78be76f78fee46f5c9e3d4a5a20e18cb1840f6bedae2f5698

/usr/src/app/sample-contracts # STARKNET_FEEDER_GATEWAY_URL=http://devnet:5050 starknet invoke --abi contract_abi.json --function increase_balance --inputs 1234 --address 0x07af9c251859892395187bd59e2
8fc8f0670bd75137e7b2a1044f2a58efaf353
Got BadRequest while trying to access https://alpha4.starknet.io/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a is not deployed."}.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/services/external_api/client.py", line 117, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a is not deployed."}
Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a is not deployed."}

/usr/src/app/sample-contracts #  starknet invoke --feeder_gateway_url http://devnet:5050 --abi contract_abi.json --function increase_balance --inputs 1234 --address 0x07af9c251859892395187bd59e28fc8f0
670bd75137e7b2a1044f2a58efaf353
Sending the transaction with max_fee: 0.000426 ETH.
Invoke transaction was sent.
Contract address: 0x07af9c251859892395187bd59e28fc8f0670bd75137e7b2a1044f2a58efaf353
Transaction hash: 0x3f7cff64174fed6fa80f0e717c4e9984b7b8d5b422359a0087a6e149441d14
```

### GATEWAY_URL
````
/usr/src/app/sample-contracts # STARKNET_GATEWAY_URL=http://devnet:5050 starknet deploy --no_wallet --contract hello.json
Deploy transaction was sent.
Contract address: 0x077e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627
Transaction hash: 0x1de77b8661c307dc16694b84107a135cfe4d68343e9a7d40030ea44d6b20f9f

/usr/src/app/sample-contracts # starknet invoke --feeder_gateway_url http://devnet:5050 --abi contract_abi.json --function increase_balance --inputs 1234 --address 0x077e9a2ca8566e25a5eaa6ce523305e30e
cfdbc2a2b1351b6b53b796970ed627
Got BadRequest while trying to access http://devnet:5050/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"message":"Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:614)\nUnknown location (pc=0:560)\nUnknown location (pc=0:214)\nUnknown location (pc=0:237)\n\nError in the called contract (0x77e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627):\nRequested contract address 0x77e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627 is not deployed.","status_code":500}
.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/services/external_api/client.py", line 117, in _send_request
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 500. Text: {"message":"Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:614)\nUnknown location (pc=0:560)\nUnknown location (pc=0:214)\nUnknown location (pc=0:237)\n\nError in the called contract (0x77e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627):\nRequested contract address 0x77e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627 is not deployed.","status_code":500}

Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"message":"Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:614)\nUnknown location (pc=0:560)\nUnknown location (pc=0:214)\nUnknown location (pc=0:237)\n\nError in the called contract (0x77e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627):\nRequested contract address 0x77e9a2ca8566e25a5eaa6ce523305e30ecfdbc2a2b1351b6b53b796970ed627 is not deployed.","status_code":500}
```

**Comment by Mahdi332453** [comment]
ok thanks.dear
