### ISSUE TITLE
Error on proof generation 

### ISSUE THREAD

**Issue by hephaistus** [starkware-libs/cairo-lang#17]
Hi I have some issues when I use ```cairo-run --proof_mode```

Here is my error
```
Traceback (most recent call last):
  File "/home/hephai/cairo_venv/bin/cairo-run", line 10, in <module>
    sys.exit(main())
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/vm/cairo_run.py", line 179, in main
    res = cairo_run(args)
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/vm/cairo_run.py", line 253, in cairo_run
    end = runner.initialize_main_entrypoint()
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/vm/cairo_runner.py", line 207, in initialize_main_entrypoint
    return self.program_base + self.program.get_label("__end__")
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/compiler/program.py", line 124, in get_label
    name=name, expected_type=LabelDefinition, full_name_lookup=full_name_lookup
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/compiler/program.py", line 113, in get_identifier
    result = self.identifiers.search(accessible_scopes=[self.main_scope], name=scoped_name)
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/compiler/identifier_manager.py", line 220, in search
    res = self._search(accessible_scopes=accessible_scopes, name=name, get_scope=False)
  File "/home/hephai/cairo_venv/lib/python3.7/site-packages/starkware/cairo/lang/compiler/identifier_manager.py", line 212, in _search
    raise MissingIdentifierError(name[:1])
starkware.cairo.lang.compiler.identifier_manager.MissingIdentifierError: Unknown identifier '__end__'.
```

Why this problem happens? and how can I fix it?

**Comment by hephaistus** [comment]
Oh I'm sorry, I should compile with --proof_mode, if I want to run with --proof_mode.
