### ISSUE TITLE
Can't Build Repo

### ISSUE THREAD

**Issue by blutooth** [starkware-libs/cairo-lang#6]
When either running pip3 install or running from docker, I get the following error:

CMake Error at CMakeLists.txt:15 (include):
  include could not find load file:

    repos/starkware-public/cmake_utils/exe_rules.cmake

CMake Error at CMakeLists.txt:16 (include):
  include could not find load file:

    repos/starkware-public/cmake_utils/python_rules.cmake

CMake Error at CMakeLists.txt:17 (include):
  include could not find load file:

    repos/starkware-public/cmake_utils/pip_rules.cmake

CMake Error at CMakeLists.txt:18 (python_get_pip_deps):
  Unknown CMake command "python_get_pip_deps".

**Comment by jflatow** [comment]
I see this is an old issue, but I am also unable to build running from `docker`:

```
#12 39.77 Building wheels for collected packages: numpy
#12 39.77   Running setup.py bdist_wheel for numpy: started
#12 39.96   Running setup.py bdist_wheel for numpy: finished with status 'error'
#12 39.96   Complete output from command /usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-s9074erm/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp9wg8oax1pip-wheel-:
#12 39.96   Running from numpy source directory.
#12 39.96   Cythonizing sources
#12 39.96   Processing numpy/random/_bounded_integers.pxd.in
#12 39.96   Processing numpy/random/bit_generator.pyx
#12 39.96   Traceback (most recent call last):
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/tools/cythonize.py", line 59, in process_pyx
#12 39.96       from Cython.Compiler.Version import version as cython_version
#12 39.96   ModuleNotFoundError: No module named 'Cython'
#12 39.96   
#12 39.96   During handling of the above exception, another exception occurred:
#12 39.96   
#12 39.96   Traceback (most recent call last):
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/tools/cythonize.py", line 235, in <module>
#12 39.96       main()
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/tools/cythonize.py", line 231, in main
#12 39.96       find_process_files(root_dir)
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/tools/cythonize.py", line 222, in find_process_files
#12 39.96       process(root_dir, fromfile, tofile, function, hash_db)
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/tools/cythonize.py", line 188, in process
#12 39.96       processor_function(fromfile, tofile)
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/tools/cythonize.py", line 64, in process_pyx
#12 39.96       raise OSError('Cython needs to be installed in Python as a module')
#12 39.96   OSError: Cython needs to be installed in Python as a module
#12 39.96   Traceback (most recent call last):
#12 39.96     File "<string>", line 1, in <module>
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/setup.py", line 513, in <module>
#12 39.96       setup_package()
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/setup.py", line 493, in setup_package
#12 39.96       generate_cython()
#12 39.96     File "/tmp/pip-build-s9074erm/numpy/setup.py", line 290, in generate_cython
#12 39.96       raise RuntimeError("Running cythonize failed!")
#12 39.96   RuntimeError: Running cythonize failed!
```
