### ISSUE TITLE
Could not build docker image.

### ISSUE THREAD

**Issue by ACChe** [starkware-libs/cairo-lang#74]
Hit to RUN 

`docker build --tag cairo .`

After a period of operation, it show lots of error to prompt build fail.

PLEASE see the below:

` 
=> ERROR [15/22] RUN ctest -V -j8                                                                                       807.6ss
------                                                                                                                          
 > [15/22] RUN ctest -V -j8:                                                                                                    
#20 0.867 UpdateCTestConfiguration  from :/app/build/Release/DartConfiguration.tcl                                              
#20 0.868 Parse Config file:/app/build/Release/DartConfiguration.tcl                                                            
#20 0.888 UpdateCTestConfiguration  from :/app/build/Release/DartConfiguration.tcl                                              
#20 0.888 Parse Config file:/app/build/Release/DartConfiguration.tcl                                                            
#20 0.890 Test project /app/build/Release
#20 0.892 Constructing a list of tests
#20 0.972 Done constructing a list of tests
#20 0.973 Updating test list for fixtures
#20 0.973 Added 0 tests to meet fixture requirements
#20 0.979 Checking test dependency graph...
#20 0.980 Checking test dependency graph end
#20 0.983 test 1
#20 0.984       Start  1: cairo_common_test
#20 0.986 
#20 0.986 1: Test command: /app/build/Release/src/starkware/cairo/common/cairo_common_test
#20 0.987 1: Test timeout computed to be: 1500
#20 0.994 test 2
#20 0.994       Start  2: cairo_run_builtins_test
#20 0.995 
#20 0.995 2: Test command: /app/build/Release/src/starkware/cairo/lang/builtins/cairo_run_builtins_test
#20 0.995 2: Test timeout computed to be: 1500
#20 0.998 test 3
#20 0.998       Start  3: cairo_compile_test
#20 0.999 
#20 0.999 3: Test command: /app/build/Release/src/starkware/cairo/lang/compiler/cairo_compile_test
#20 0.999 3: Test timeout computed to be: 1500
#20 1.002 test 4
#20 1.003       Start  4: cairo_tracer_test
#20 1.003 
#20 1.003 4: Test command: /app/build/Release/src/starkware/cairo/lang/tracer/cairo_tracer_test
#20 1.003 4: Test timeout computed to be: 1500
#20 1.007 test 5
#20 1.008       Start  5: cairo_vm_test
#20 1.008 
#20 1.008 5: Test command: /app/build/Release/src/starkware/cairo/lang/vm/cairo_vm_test
#20 1.008 5: Test timeout computed to be: 1500
#20 1.025 test 6
#20 1.025       Start  6: fact_checker_test
#20 1.026 
#20 1.026 6: Test command: /app/build/Release/src/starkware/cairo/sharp/fact_checker_test
#20 1.026 6: Test timeout computed to be: 1500
#20 1.060 test 7
#20 1.060       Start  7: sharp_client_lib_test
#20 1.060 
#20 1.060 7: Test command: /app/build/Release/src/starkware/cairo/sharp/sharp_client_lib_test
#20 1.060 7: Test timeout computed to be: 1500
#20 1.077 test 8
#20 1.078       Start  8: starkware_python_utils_test
#20 1.078 
#20 1.078 8: Test command: /app/build/Release/src/starkware/python/starkware_python_utils_test
#20 1.078 8: Test timeout computed to be: 1500
#20 7.881 8: ============================= test session starts ==============================
#20 7.882 8: platform linux -- Python 3.7.13, pytest-7.0.0, pluggy-1.0.0
#20 7.946 8: rootdir: /app/build/Release
#20 7.946 8: plugins: asyncio-0.18.0
#20 7.946 8: asyncio: mode=legacy
#20 16.59 8: collected 33 items
#20 16.59 8: 
#20 16.62 8: src/starkware/python/starkware_python_utils_test_venv-site/starkware/python/expression_string_test.py . [  3%]
#20 16.64 8:                                                                          [  3%]
#20 16.65 8: src/starkware/python/starkware_python_utils_test_venv-site/starkware/python/math_utils_test.py . [  6%]
.......
.......
.......
#20 805.9 18:     DeprecationWarning,
#20 805.9 18: 
#20 805.9 18: python_pip/python3.7/pip_pytest_asyncio/pytest_asyncio/plugin.py:228
#20 805.9 18:   /app/build/Release/python_pip/python3.7/pip_pytest_asyncio/pytest_asyncio/plugin.py:228: DeprecationWarning: '@pytest.fixture' is applied to <fixture starknet, file=/app/build/Release/src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/starknet_test.py, line=13> in 'legacy' mode, please replace it with '@pytest_asyncio.fixture' as a preparation for switching to 'strict' mode (or use 'auto' mode to seamlessly handle all these fixtures as asyncio-driven).
#20 805.9 18:     DeprecationWarning,
#20 805.9 18: 
#20 805.9 18: python_pip/python3.7/pip_pytest_asyncio/pytest_asyncio/plugin.py:228
#20 805.9 18:   /app/build/Release/python_pip/python3.7/pip_pytest_asyncio/pytest_asyncio/plugin.py:228: DeprecationWarning: '@pytest.fixture' is applied to <fixture contract, file=/app/build/Release/src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/starknet_test.py, line=18> in 'legacy' mode, please replace it with '@pytest_asyncio.fixture' as a preparation for switching to 'strict' mode (or use 'auto' mode to seamlessly handle all these fixtures as asyncio-driven).
#20 805.9 18:     DeprecationWarning,
#20 805.9 18: 
#20 805.9 18: -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
#20 805.9 18: =========================== short test summary info ============================
#20 805.9 18: ERROR src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/mock_starknet_messaging_test.py::test_mock_send_message_from_l2
#20 805.9 18: ERROR src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/mock_starknet_messaging_test.py::test_mock_consume_message_to_l2
#20 805.9 18: ERROR src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/postman_test.py::test_postman_l1_to_l2_positive_flow
#20 805.9 18: ERROR src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/postman_test.py::test_postman_l1_to_l2_another_mock_starknet_messaging_contract
#20 805.9 18: ERROR src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/starknet/testing/postman_test.py::test_postman_l2_to_l1_positive_flow
#20 805.9 18: ============= 9 passed, 11 warnings, 5 errors in 667.18s (0:11:07) =============
#20 806.2 18: Exception ignored in: <function Ganache.__del__ at 0x400e795200>
#20 806.2 18: Traceback (most recent call last):
#20 806.2 18:   File "/app/build/Release/src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/eth/eth_test_utils.py", line 96, in __del__
#20 806.2 18:     self.stop()
#20 806.2 18:   File "/app/build/Release/src/starkware/starknet/testing/starknet_testing_test_venv-site/starkware/eth/eth_test_utils.py", line 99, in stop
#20 806.2 18:     if not self.is_alive:
#20 806.2 18: AttributeError: 'Ganache' object has no attribute 'is_alive'
#20 807.4 20/20 Test #18: starknet_testing_test ..................***Failed  686.31 sec
#20 807.4 
#20 807.4 95% tests passed, 1 tests failed out of 20
#20 807.4 
#20 807.4 Total Test time (real) = 806.49 sec
#20 807.4 
#20 807.4 The following tests FAILED:
#20 807.4 	 18 - starknet_testing_test (Failed)
#20 807.4 Errors while running CTest
#20 807.4 Output from these tests are in: /app/build/Release/Testing/Temporary/LastTest.log
#20 807.4 Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
------
executor failed running [/bin/sh -c ctest -V -j8]: exit code: 8`

**Comment by federicosan** [comment]
this is happening to me too, macos laptop
